#%RAML 1.0
---
title: Torrent API
mediaType: application/json
version: v1.0
/ping:
  get: {}
/torrents:
  /{torrentHash}:
    /events:
      get:
        displayName: Torrent status
        description: Subscribe to torrent updates
    /info:
      get:
        displayName: Get file info
        description: Torrent info about file
        uriParameters:
          path:
            example: screenshots/screenshot1.jpg
            type: string
            description: path to file in torrent
            required: true
    /stream:
      get:
        displayName: Get file
        description: Serve file from torrent
        uriParameters:
          path:
            example: screenshots/screenshot1.jpg
            type: string
            description: path to file in torrent
            required: true
    get:
      displayName: Torrent info
      description: Return info about torrent
  /add:
    get:
      displayName: Add magnet
      description: Add torrent via magnet link
      uriParameters:
        magnet:
          example: magnet%3A%3Fxt%3Durn%3Abtih%3A40448d478d9203a3919b0900e7fbb9e8748dcdf9%26dn%3Dubuntu.iso
          type: string
          description: urlencoded magnet link
          required: true
    post:
      displayName: Add torrent
      description: Add torrent via file upload
      body:
        torrent:
          type: file
          description: torrent content
  get:
    displayName: List torrents
    description: Return list of torrents

