[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/dht"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/missinggo"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/tagflag"

[[constraint]]
  branch = "master"
  name = "github.com/anacrolix/torrent"

[[constraint]]
  name = "github.com/go-chi/chi"
  branch = "master"

[[constraint]]
  name = "github.com/go-chi/docgen"
  branch = "master"

[[constraint]]
  name = "github.com/go-chi/render"
  branch = "master"

[[constraint]]
  name = "github.com/rakyll/statik"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
